### ISSUE TITLE
Compatibility between xt::pytensor and xt::xtensor

### ISSUE THREAD

**Issue by yoshipon** [QuantStack/xtensor-python#112]
Thank you for developing xtensor and xtensor-python, which are very practical libraries.
In some cases, I want to write the following functions and export to Python with pybind11:
```
void foo(const xt::pytensor<double, 1> &a)
{
  xt::xtensor<double, 1> b = 0.5 * a;
}
```
This function can be compiled with g++ (5.4.0@ubuntu 16.04).
However, the following Python code stops with Segmentation Fault (core dumped):
`foo(np.array([1]))`
although this code works correctly:
`foo(np.array([1,2,3]))`

If you have some ideas about this bug and don't have enough time for debugging,
  I would like to try fixing according to your comments.

**Comment by JohanMabille** [comment]
Thank you for reporting!
Which version of `xtensor` and `xtensor-python` do you use ?

**Comment by yoshipon** [comment]
Thank you for your reply.

I am using latest version of them.
I cloned their git repositories just few minutes ago and installed with cmake.

**Comment by JohanMabille** [comment]
Ok, it seems the bug is in xtensor. I can reproduce it with the following code:

```cpp
xt::xtensor<int, 1> a = { 1 };
xt::xtensor<int, 1> res = 2 * a;
```

I'm working on a fix.

**Comment by JohanMabille** [comment]
@yoshipon the bug has been fixed in `xtensor` master. Can you confirm it works for you ?

**Comment by yoshipon** [comment]
@JohanMabille Thank you very much for your super-fast response.
I confirmed that now the problem is fixed.

**Comment by JohanMabille** [comment]
you're welcome!

**Comment by SylvainCorlay** [comment]
@yoshipon we have made a patch release of xtensor with this bugfix.

`xtensor 0.11.3`.

The conda recipe is building on conda forge.

**Comment by SylvainCorlay** [comment]
> I cloned their git repositories just few minutes ago and installed with cmake.

Cool!

If you are working with other xtensor projects such as xtensor-python, we recommend using the latest the latest tagged version in general.

Also, we have a fairly active chat room here: https://gitter.im/QuantStack/Lobby !

**Comment by yoshipon** [comment]
@SylvainCorlay Thank you for informing about them!
