### ISSUE TITLE
example 2 has ImportError: undefined symbol xtensor_python_ARRAY_API

### ISSUE THREAD

**Issue by Roger-luo** [QuantStack/xtensor-python#136]
Hi guys, I tried the example 2. But I got this ImportError. It seems that xtensor_python_ARRAY_API is not defined. I tried `grep` this in both `xtensor` and `xtensor-python` but I cannot find its definition.

It is used here in `pycontainer.hpp`

```c++
#define PY_ARRAY_UNIQUE_SYMBOL xtensor_python_ARRAY_API
```

**Comment by SylvainCorlay** [comment]
Can you please provide more details about this?

(Version of Python, Numpy, OS, more comprehensive error message?)

**Comment by Roger-luo** [comment]
This is the version. I did a little search, it seems that the macro `PY_ARRAY_UNIQUE_SYMBOL` should be defined by numpy?

Python Version: Python 3.6.2
Numpy Version: 1.13.1

```shell
uname -a
4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by JohanMabille** [comment]
According to [this](https://github.com/QuantStack/xtensor-python/blob/d2668d36acd9bb8fee39305589548fc63ddb7022/docs/source/numpy_capi.rst#L48), it seems that we forgot to define `FORCE_IMPORT_ARRAY` and to call `xt::import_numpy();` in the module definition, as it is done in the first example.

@Roger-luo can you confirm that the first example works? If so can you define the `FORCE_IMPORT_ARRAY` symbol and call `xt::import_numpy();` in the module definition of the example 2, like it is done in example 1? This should fix the problem.

**Comment by Roger-luo** [comment]
@JohanMabille Thanks, it works now!

**Comment by SylvainCorlay** [comment]
@JohanMabille qre you changing the readme example?

**Comment by JohanMabille** [comment]
Yep I make a PR
