### ISSUE TITLE
Is there any custom type cast defined for `xtensor` and `xarray`? 

### ISSUE THREAD

**Issue by Roger-luo** [QuantStack/xtensor-python#138]
I tried this based on example 1, but it seems that there no type casters like pybind11's `stl.h` which will auto-cast `std::vector` and etc. to python types.

```c++
double _sum_of_sines(xt::xarray<double> &m)
{
  auto sines = xt::sin(m);
  return std::accumulate(sines.cbegin(), sines.cend(), 0.0);
}

double sum_of_sines(xt::pyarray<double> &m)
{
  return _sum_of_sines(m.cast<xt::xarray<double>>());
}
```

**Comment by SylvainCorlay** [comment]
You don't need them actually. You can simply make _sum_of_sines tahe an argument of type `xexpression<D>` and it will work with any array expression including xarray, pyarray and others (expressions backed by file system operations, data base calls, or comouted on the fly like linspace).

You can read the blog post on polyglot scientific comouting with xtensor.

**Comment by SylvainCorlay** [comment]
Writing your generic code with expressions as inputs will make it more generic and allow for exposing it to julia and R as well.

**Comment by Roger-luo** [comment]
@SylvainCorlay  What do you mean take an argument of type `xexpression<D>`? But this won't compile...

```c++
template <typename D>
double _sum_of_sines(xt::xexpression<D> &m)
{
  auto sines = xt::sin(m);
  return std::accumulate(sines.cbegin(), sines.cend(), 0.0);
}

double sum_of_sines(xt::pyarray<double> &m)
{
  return _sum_of_sines(m);
}
```


And I just read how `xmath.h` implemented, I got this one works:

```c++
template <typename E>
double _sum_of_sines(E &&m)
{
  auto sines = xt::sin(m);
  return std::accumulate(sines.cbegin(), sines.cend(), 0.0);
}

double sum_of_sines(xt::pyarray<double> &m)
{
  return _sum_of_sines(m);
}
```

**Comment by wolfv** [comment]
Hey @Roger-luo ,

I believe you're missing a `derived_cast()`. 

Like this:

```
template <typename D>
double _sum_of_sines(xt::xexpression<D> &m)
{
  auto& d_arr = m.derived_cast();
  auto sines = xt::sin(d_arr);
  return std::accumulate(sines.cbegin(), sines.cend(), 0.0);
}
```

**Comment by SylvainCorlay** [comment]
You can check out the article here:

http://quantstack.net/c++/2017/05/30/polyglot-scientific-computing-with-xtensor.html

This is something that we will be adding to the narrative documentation soon.

**Comment by Roger-luo** [comment]
@wolfv Oh, thanks, it works. So I guess both implementation would works. But I have to specify the type to be `xexpression<pyarray<double>>` while binding it to python according to the post. 

@SylvainCorlay this is a really cool post. I'm developing a quantum many-body physics toolkit and I was trying to write something similar based on [mshadow](https://github.com/dmlc/mshadow), just find your guys have already done. I'll continue my project with your package. Thanks a lot.

**Comment by Roger-luo** [comment]
@SylvainCorlay  BTW, the example in the post does not compile. there is no need for `xexpression` in the binding part.

The original example won't compile, because previously `pyarray` is defined here

```c++
namespace py = pybind11;
using pyarray_type = xt::pyarray<double>;
```

the following is actually not correct.

```c++
template <class E1, class E2>
double xprocess(const xt::xexpression<E1>& e1,
                const xt::xexpression<E2>& e2)
{
    const E1& m1 = e1.derived_cast();
    const E2& m2 = e2.derived_cast();
    // Operate on m1 and m2 using the numpy-style xtensor API.
}

PYBIND11_PLUGIN(cppprocess)
{
    xt::import_numpy();
    py::module m("cppprocess", "cppprocess extension module");
    m.def("process", xprocess<xt::xexpression<pyarray_type>,
                              xt::xexpression<pyarray_type>>);
    return m.ptr();
}
```

I get this one works

```c++
template <class E1, class E2>
double xprocess(const xt::xexpression<E1> &e1,
                const xt::xexpression<E2> &e2)
{
  const E1 &m1 = e1.derived_cast();
  const E2 &m2 = e2.derived_cast();
  // Operate on m1 and m2 using the numpy-style xtensor API.
}

template <typename DType>
using pyarray = typename xt::pyarray<DType>;
PYBIND11_MODULE(_core, m)
{
  
  m.doc() = "qmtk c++ core";

  xt::import_numpy();
  m.def("sum_of_sines", xprocess<pyarray<double>, pyarray<double>>,
        "Sum the sines of the input values");
}
```

**Comment by SylvainCorlay** [comment]
Note: the difference with the macros used are due to the post being quite old, and APIs of pybind11 having changed in the mean time.

We will include the tutorial in the documentation soon which will evolve with the code base and dependencies.
