### ISSUE TITLE
doxygen warning for pyvectorize docs

### ISSUE THREAD

**Issue by anntzer** [QuantStack/xtensor-python#14]
See https://xtensor-python.readthedocs.io/en/latest/pyvectorize.html
```
doxygenfunction: Unable to resolve multiple matches for function “xt::pyvectorize” with arguments () in doxygen xml output for project “xtensor-python” from directory: ../xml. Potential matches:
<elided>
```

**Comment by SylvainCorlay** [comment]
@anntzer thanks for reporting. We are aware of this issue and have an open issue in breathe: https://github.com/michaeljones/breathe/issues/289

If you know the best way to get around it, that would be geat...

**Comment by anntzer** [comment]
I have no idea...

**Comment by JohanMabille** [comment]
I have a workaround [here](https://github.com/michaeljones/breathe/issues/289).
