### ISSUE TITLE
pyarray and pytensor names in auto-generated docstring

### ISSUE THREAD

**Issue by PerretB** [QuantStack/xtensor-python#141]
Pyarray and pytensor rely on pybind11 `make_caster<T>::name()` to determine the string representation of its `value_type` (which is then used for the auto-generated docstring). However, `make_caster` assigns the name "int" to every integral type and "float" to every floating type (except for "char"->"str" and "bool"->"bool"). 

While this makes perfect sens for vanilla Python, this becomes confusing with Numpy where the precise numeric type is important. For example, defining the two overloaded `test` functions in the module `m`:

```cpp
m.def("test", [](xt::pyarray<int>&a){});
m.def("test", [](xt::pyarray<long>&a){});
```
leads to the following docstring:

```
    test(*args, **kwargs)
    Overloaded function.
    
    1. test(arg0: numpy.ndarray[int]) -> None
    2. test(arg0: numpy.ndarray[int]) -> None
```
where the two overloads seem to have an identical signature.

Would it be possible to bypass pybind11 `make_caster` for types that corresponds to numpy dtypes  such that we would get a correct docstring ? (something like: )

```
    1. test(arg0: numpy.ndarray[int32]) -> None
    2. test(arg0: numpy.ndarray[int64]) -> None
```

**Comment by SylvainCorlay** [comment]
Thanks @PerretB I agree that specifying the `int32` and `int64` flavors in the python docstrings would make a lot more sense.

**Comment by wolfv** [comment]
Done! :)
