### ISSUE TITLE
fixed-dimensionality pytensor

### ISSUE THREAD

**Issue by anntzer** [QuantStack/xtensor-python#15]
Just as `xtensor` provides both `xarray<T>` and `xtensor<T, n>`, it would be nice if `xtensor-python` provided a fixed-dimensionality container (that would raise at call time if an array(-like) with invalid dimensionality was passed in from python).

**Comment by SylvainCorlay** [comment]
So the specificity of `xtensor<T, n>` is that shape and strides are stack-allocated which makes it more efficient than `xarray` with the drawback of not being reshapable to other dimensions (although broadcastable to shapes of same dimension.)

`pyarray` is a wrapper on the buffer protocol pointers from numpy, which does not really correspond to that.

One thing that we could do is provides a new types that validates the dimension at runtime for pyarrays... Although I wonder if it would not be better to provide documentation on how to validated preconditions on passed pyarrays....

**Comment by anntzer** [comment]
Documentation would be fine too.

**Comment by SylvainCorlay** [comment]
@anntzer I am reconsidering this. There are important performance benefits to fixed-dimension arrays which we should expose to numpy users. Will work on this in next version.

**Comment by JohanMabille** [comment]
we might consider something similar to [this](https://github.com/ndarray/ndarray/blob/master/include/ndarray/pybind11.h#L63).

**Comment by SylvainCorlay** [comment]
^ @anntzer this has been implemented
