### ISSUE TITLE
from pytensor to xtensor without copying the underlying data and vice-versa

### ISSUE THREAD

**Issue by bordingj** [QuantStack/xtensor-python#161]
Is there a way to go from a xt::pytensor to xt::xtensor and back again without copying the underlying data ?
If so, it would be nice with some documentation on how to do it. If not, then I have a feature request :) .

**Comment by wolfv** [comment]
Hi bordingj, 

no, there is no way to do that. but you can use all functions that you have on xtensor on the pytensor as well. 

If you want to write expression agnostic code, writing templated code in this fashion is recommended:

```cpp
template <class T>
auto func(xexpression<T>& expr)
{
    auto& de = expr.derived_cast();
    de[0] += 123;
    return de;
}
```

**Comment by bordingj** [comment]
I understand. Thank you.
