### ISSUE TITLE
Python3 Support?

### ISSUE THREAD

**Issue by apepkuss** [QuantStack/xtensor-python#200]
I'd like to install xtensor-python in my python3.6.8 dev environment via conda. But it seems that the latest release (0.23.1) does not support python3. The only available package I can find by conda search and pip search is xtensor-python-0.12.1. Is it correct? If I am wrong, please correct me. Thanks!

**Comment by SylvainCorlay** [comment]
xtensor-python definitely supports python 3.

What makes you think otherwise? I am confused.

**Comment by JohanMabille** [comment]
This might be due to a conflict between packages you have installed. Can you try to force the version of xtensor-python to see what happens? `conda install xtensor-python==0.23.1 -c conda-forge`

**Comment by apepkuss** [comment]
@SylvainCorlay @JohanMabille
Thanks for your reply. I made a stupid mistake when I conda-searched xtensor-python. You're right, it works for Python2 and 3. Thanks again.
