### ISSUE TITLE
interoperate with numpy arrays?

### ISSUE THREAD

**Issue by nbecker** [QuantStack/xtensor-python#25]
How can I use xtensor-python with numpy arrays?  I'd want to call functions implemented with xtensor c++ from python passing numpy arrays, and also return numpy arrays to python.

Is there a discussion or mail list for these questions?

Thanks

**Comment by SylvainCorlay** [comment]
@nbecker that is the whole point of `xtensor-python`.

You can check out the example from the Readme, which does exactly what you are describing.

If you want to start off from a template project exposing your work as a C++ extension, you can directly use the project cookiecutter.

**Comment by SylvainCorlay** [comment]
You can join the gitter chat for xtensor here: https://gitter.im/QuantStack/Lobby

**Comment by SylvainCorlay** [comment]
`xtensor-python` makes numpy arrays compatible with xtensor. You can even reshape them inplace.

We are working hard to implement a large part of numpy functionalities in xtensor

Check out the example C++ notebook here:

http://nbviewer.jupyter.org/github/QuantStack/xtensor/blob/master/notebooks/xtensor.ipynb

**Comment by SylvainCorlay** [comment]
Closing since you found you way to the discussion channels!

**Comment by jingpengw** [comment]
I have not find the documentation about return pytensor as numpy array.

**Comment by jingpengw** [comment]
I tried to return two pytensors, but got error:
```
Numpy: unable to create ndarray
```
my code is like this:
```
py::make_tuple(pytensor1,  pytensor2)
```

**Comment by wolfv** [comment]
what are the shapes of your pytensors?

if you write this code:


```
xt::pyarray<double> test(xt::pyarray<double>& var)
{
    return var * 2;
}
```

This should return you a numpy array.

**Comment by jingpengw** [comment]
thanks, I just find that my issue is not return, it is getting the numpy array to c++. I have one function working, but not another one getting two numpy arrays to c++.
