### ISSUE TITLE
Configuration feedback

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [QuantStack/xtensor-python#74]
- when installing the latest xtensor using conda, it does not appear to install its header files anywhere in the conda env include
- the cookiecutter template does not refer to any xtensor include path either
- when I clone the latest xtensor master or the 0.8.4 release commit, and add its include path to my cookiecutter instance, I get the following when running 'python setup.py build_ext -fi':

`running build_ext
building 'pyaabbtree' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Eelco\Miniconda3\envs\pyaabbtree\Include -IC:\Users\Eelco\AppData\
Roaming\Python\Python36\Include -IC:\Users\Eelco\Miniconda3\envs\pyaabbtree\lib\site-packages\numpy\core\include -IC:\Users\Eelco\Dropbox\Git\xtensor\include -IC:\Users\Eelco\Miniconda3\env
s\pyaabbtree\include -IC:\Users\Eelco\Miniconda3\envs\pyaabbtree\include -IC:\Users\Eelco\Miniconda3\envs\pyaabbtree\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUD
E" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETF
XSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include
\\winrt" /EHsc /Tpsrc/main.cpp /Fobuild\temp.win-amd64-3.6\Release\src/main.obj /EHsc /DVERSION_INFO=\"0.0.1\"
main.cpp
c:\users\eelco\dropbox\git\xtensor\include\xtensor\xfunction.hpp(132): error C2039: 'layout_type': is not a member of 'xt::pyarray<double>'
src/main.cpp(18): note: see declaration of 'xt::pyarray<double>'
src/main.cpp(25): note: see reference to class template instantiation 'xt::xfunction<std::plus<double>,double,const xt::pyarray<double> &,xt::xscalar<const int>>' being compiled
c:\users\eelco\dropbox\git\xtensor\include\xtensor\xfunction.hpp(132): error C2065: 'layout_type': undeclared identifier
c:\users\eelco\dropbox\git\xtensor\include\xtensor\xfunction.hpp(133): error C2039: 'contiguous_layout': is not a member of 'xt::pyarray<double>'
src/main.cpp(18): note: see declaration of 'xt::pyarray<double>'
c:\users\eelco\dropbox\git\xtensor\include\xtensor\xfunction.hpp(133): error C2065: 'contiguous_layout': undeclared identifier
c:\users\eelco\dropbox\git\xtensor\include\xtensor\xfunction.hpp(133): error C2975: 'B': invalid template argument for 'xt::and_c', expected compile-time constant expression
c:\users\eelco\dropbox\git\xtensor\include\xtensor\xutils.hpp(210): note: see declaration of 'B'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
`

Am I using incompatible versions of the various packages? Sadly I cant see right away if this is some form of trivial error without familiarizing myself with the codebase first.

**Comment by SylvainCorlay** [comment]
I am surprised that you don't see the headers in the conda package

 - the package checks for the presence of the headers at build time.
 - I checked again and the headers are included in the windows `tar.gz` on anaconda.org (since it is the platform that you are using).

Regarding the use of xtensor from source, I would recommend checking out tags, instead of the tip of master.
Master reflects new unreleased features that will require updates in xtensor-python, and from what I see, this is the reason for your error message.

**Comment by SylvainCorlay** [comment]
Ah, I found an issue with the cookie-cutter: 

After `os.path.join(sys.prefix, 'include')`, please try adding `os.path.join(sys.prefix, 'Library', 'include')`.

I recommend using the conda-packages which reflect stable releases.

**Comment by EelcoHoogendoorn** [comment]
Ah indeed; library/include is indeed where it is at!

**Comment by SylvainCorlay** [comment]
Pfiou, closing. Thanks for the feedback.

**Comment by EelcoHoogendoorn** [comment]
With a footnote: I seem to recall that there are some python2/3 win/linux differences regarding the python directory structure that may be relevant to this, so simply hardcoding the relative path might not work under all circumstances.
